environment:
  matrix:
    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:
  - "%PYTHON%\\scripts\\conda.exe config --set always_yes true"
  - "%PYTHON%\\scripts\\conda.exe install numpy pytest scikit-image pillow"
  - "%PYTHON%\\scripts\\conda.exe install -c conda-forge pytest-cov"
  - "%PYTHON%\\scripts\\pip.exe install py-vox-io"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest --cov=mpstool --cov-report=term-missing"

artifacts:
  - path: dist\*
